language: node_js

os:
  - linux
  - osx

notifications:
  email:
    on_success: never
    on_failure: always

node_js:
  - '6.0'
  - '7.0'
  - '8.0'
  - '9.0'
  - '10.0'

before_script:
  - npm install

script:
  - npm run test
  - npm run build
